#!/usr/bin/env python3
"""Build platform-specific rule sets from source/*.list.

Source format (one rule per line, no policy):
    # NAME: Xiaohongshu
    # DESC: ...
    # POLICY: DIRECT        (optional, used for one-click import links)
    DOMAIN-SUFFIX,example.com
    IP-CIDR,1.2.3.0/24

Outputs:
    rules/surge/<Name>.list   Surge RULE-SET
    rules/loon/<Name>.list    Loon remote rule
    rules/quanx/<Name>.list   Quantumult X filter_remote
    rules/clash/<Name>.yaml   Clash / Mihomo rule-provider (behavior: classical)
    README.md                 one-click import table between IMPORT markers

Usage:
    python3 scripts/build.py           # build
    python3 scripts/build.py --check   # fail if outputs are stale
"""
import json
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "source"
OUT = ROOT / "rules"
REPO_URL = "https://github.com/zwithz/rules"
RAW_BASE = "https://raw.githubusercontent.com/zwithz/rules/main/rules"
CDN_BASE = "https://cdn.jsdelivr.net/gh/zwithz/rules@main/rules"
README = ROOT / "README.md"
IMPORT_BEGIN = "<!-- IMPORT:BEGIN (generated by scripts/build.py) -->"
IMPORT_END = "<!-- IMPORT:END -->"
# QuanX built-in policies are lower case; anything else is used as-is
# (e.g. a policy group name defined in the user's config).
QUANX_POLICY = {"DIRECT": "direct", "PROXY": "proxy", "REJECT": "reject"}

SUPPORTED = {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD", "IP-CIDR", "IP-CIDR6"}
IP_TYPES = {"IP-CIDR", "IP-CIDR6"}
QUANX_TYPE = {
    "DOMAIN": "HOST",
    "DOMAIN-SUFFIX": "HOST-SUFFIX",
    "DOMAIN-KEYWORD": "HOST-KEYWORD",
    "IP-CIDR": "IP-CIDR",
    "IP-CIDR6": "IP6-CIDR",
}


def parse(path):
    meta, rules, seen = {}, [], set()
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            body = line.lstrip("#").strip()
            if ":" in body:
                k, v = body.split(":", 1)
                if k.strip().upper() in {"NAME", "DESC", "UPDATED", "POLICY"}:
                    meta[k.strip().upper()] = v.strip()
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) != 2 or parts[0].upper() not in SUPPORTED or not parts[1]:
            sys.exit(f"{path.name}:{n}: invalid rule: {raw!r} "
                     f"(expected TYPE,value; TYPE in {sorted(SUPPORTED)})")
        rule = (parts[0].upper(), parts[1].lower() if not parts[0].upper() in IP_TYPES else parts[1])
        if rule in seen:
            print(f"warning: {path.name}:{n}: duplicate {rule}", file=sys.stderr)
            continue
        seen.add(rule)
        rules.append(rule)
    meta.setdefault("NAME", path.stem)
    if not rules:
        sys.exit(f"{path.name}: no rules")
    return meta, rules


def header(meta, rules, c="#"):
    counts = {}
    for t, _ in rules:
        counts[t] = counts.get(t, 0) + 1
    lines = [f"{c} NAME: {meta['NAME']}"]
    if meta.get("DESC"):
        lines.append(f"{c} DESC: {meta['DESC']}")
    if meta.get("UPDATED"):
        lines.append(f"{c} UPDATED: {meta['UPDATED']}")
    lines.append(f"{c} TOTAL: {len(rules)}")
    lines += [f"{c} {t}: {n}" for t, n in sorted(counts.items())]
    lines.append(f"{c} SOURCE: {REPO_URL}")
    lines.append(f"{c} GENERATED by scripts/build.py, do not edit by hand")
    return lines


def render(meta, rules):
    name = meta["NAME"]
    h = header(meta, rules)

    def surge_like(t, v):
        return f"{t},{v},no-resolve" if t in IP_TYPES else f"{t},{v}"

    surge = h + [surge_like(t, v) for t, v in rules]
    # Loon uses the same syntax as Surge for remote rules.
    loon = h + [surge_like(t, v) for t, v in rules]
    # QuanX filter_remote requires a policy column; use the rule name and
    # override it with force-policy in the client config.
    quanx = h + [f"{QUANX_TYPE[t]},{v},{name}" for t, v in rules]
    clash = h + ["payload:"] + [
        f"  - {t},{v},no-resolve" if t in IP_TYPES else f"  - {t},{v}" for t, v in rules
    ]
    return {
        OUT / "surge" / f"{name}.list": surge,
        OUT / "loon" / f"{name}.list": loon,
        OUT / "quanx" / f"{name}.list": quanx,
        OUT / "clash" / f"{name}.yaml": clash,
    }


def import_links(meta, base):
    """Return (loon, quanx) one-click import links.

    Both use the apps' official https universal links, because GitHub strips
    custom schemes (loon://, quantumult-x://) from rendered Markdown.
    """
    name = meta["NAME"]
    policy = meta.get("POLICY", "PROXY")
    loon_url = f"{base}/loon/{name}.list"
    loon = f"https://www.nsloon.com/openloon/import?rules={quote(loon_url, safe='')}"
    qx_line = (f"{base}/quanx/{name}.list, tag={name}, "
               f"force-policy={QUANX_POLICY.get(policy.upper(), policy)}, "
               f"update-interval=86400, opt-parser=false, enabled=true")
    qx_json = json.dumps({"filter_remote": [qx_line]}, ensure_ascii=False,
                         separators=(",", ":"))
    quanx = ("https://quantumult.app/x/open-app/add-resource?remote-resource="
             + quote(qx_json, safe=""))
    return loon, quanx


def render_import_table(metas):
    rows = [
        "| 名称 | 策略 | Loon | Quantumult X |",
        "|---|---|---|---|",
    ]
    for meta in metas:
        name = meta["NAME"]
        policy = f"`{meta['POLICY']}`" if meta.get("POLICY") else "-"
        loon, qx = import_links(meta, RAW_BASE)
        loon_cdn, qx_cdn = import_links(meta, CDN_BASE)
        rows.append(
            f"| [{name}](source/{name}.list) | {policy} "
            f"| [一键导入]({loon}) · [CDN]({loon_cdn}) "
            f"| [一键导入]({qx}) · [CDN]({qx_cdn}) |"
        )
    return "\n".join([IMPORT_BEGIN, ""] + rows + ["", IMPORT_END])


def render_readme(metas):
    text = README.read_text(encoding="utf-8")
    start, end = text.find(IMPORT_BEGIN), text.find(IMPORT_END)
    if start < 0 or end < start:
        sys.exit(f"README.md: missing {IMPORT_BEGIN!r} / {IMPORT_END!r} markers")
    return text[:start] + render_import_table(metas) + text[end + len(IMPORT_END):]


def main():
    check = "--check" in sys.argv
    files, metas = {}, []
    for src in sorted(SRC.glob("*.list")):
        meta, rules = parse(src)
        metas.append(meta)
        files.update(render(meta, rules))
    stale = []
    readme = render_readme(metas)
    if README.read_text(encoding="utf-8") != readme:
        stale.append(README.relative_to(ROOT))
        if not check:
            README.write_text(readme, encoding="utf-8")
    for path, lines in files.items():
        text = "\n".join(lines) + "\n"
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    # remove outputs whose source was deleted
    for p in OUT.glob("*/*"):
        if p.is_file() and p not in files:
            stale.append(p.relative_to(ROOT))
            if not check:
                p.unlink()
    if check and stale:
        sys.exit("stale outputs, run python3 scripts/build.py:\n  " +
                 "\n  ".join(map(str, stale)))
    print(f"{len(files)} files, {len(stale)} {'stale' if check else 'updated'}")


if __name__ == "__main__":
    main()
