#!/usr/bin/env python3
"""Build platform-specific rule sets from source/*.list.

Source format (one rule per line, no policy):
    # NAME: Xiaohongshu
    # DESC: ...
    DOMAIN-SUFFIX,example.com
    IP-CIDR,1.2.3.0/24

Outputs:
    rules/surge/<Name>.list   Surge RULE-SET
    rules/loon/<Name>.list    Loon remote rule
    rules/quanx/<Name>.list   Quantumult X filter_remote
    rules/clash/<Name>.yaml   Clash / Mihomo rule-provider (behavior: classical)

Usage:
    python3 scripts/build.py           # build
    python3 scripts/build.py --check   # fail if outputs are stale
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "source"
OUT = ROOT / "rules"
REPO_URL = "https://github.com/zwithz/rules"

SUPPORTED = {"DOMAIN", "DOMAIN-SUFFIX", "DOMAIN-KEYWORD", "IP-CIDR", "IP-CIDR6"}
IP_TYPES = {"IP-CIDR", "IP-CIDR6"}
QUANX_TYPE = {
    "DOMAIN": "HOST",
    "DOMAIN-SUFFIX": "HOST-SUFFIX",
    "DOMAIN-KEYWORD": "HOST-KEYWORD",
    "IP-CIDR": "IP-CIDR",
    "IP-CIDR6": "IP6-CIDR",
}


def parse(path):
    meta, rules, seen = {}, [], set()
    for n, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        if line.startswith("#"):
            body = line.lstrip("#").strip()
            if ":" in body:
                k, v = body.split(":", 1)
                if k.strip().upper() in {"NAME", "DESC", "UPDATED"}:
                    meta[k.strip().upper()] = v.strip()
            continue
        parts = [p.strip() for p in line.split(",")]
        if len(parts) != 2 or parts[0].upper() not in SUPPORTED or not parts[1]:
            sys.exit(f"{path.name}:{n}: invalid rule: {raw!r} "
                     f"(expected TYPE,value; TYPE in {sorted(SUPPORTED)})")
        rule = (parts[0].upper(), parts[1].lower() if not parts[0].upper() in IP_TYPES else parts[1])
        if rule in seen:
            print(f"warning: {path.name}:{n}: duplicate {rule}", file=sys.stderr)
            continue
        seen.add(rule)
        rules.append(rule)
    meta.setdefault("NAME", path.stem)
    if not rules:
        sys.exit(f"{path.name}: no rules")
    return meta, rules


def header(meta, rules, c="#"):
    counts = {}
    for t, _ in rules:
        counts[t] = counts.get(t, 0) + 1
    lines = [f"{c} NAME: {meta['NAME']}"]
    if meta.get("DESC"):
        lines.append(f"{c} DESC: {meta['DESC']}")
    if meta.get("UPDATED"):
        lines.append(f"{c} UPDATED: {meta['UPDATED']}")
    lines.append(f"{c} TOTAL: {len(rules)}")
    lines += [f"{c} {t}: {n}" for t, n in sorted(counts.items())]
    lines.append(f"{c} SOURCE: {REPO_URL}")
    lines.append(f"{c} GENERATED by scripts/build.py, do not edit by hand")
    return lines


def render(meta, rules):
    name = meta["NAME"]
    h = header(meta, rules)

    def surge_like(t, v):
        return f"{t},{v},no-resolve" if t in IP_TYPES else f"{t},{v}"

    surge = h + [surge_like(t, v) for t, v in rules]
    # Loon uses the same syntax as Surge for remote rules.
    loon = h + [surge_like(t, v) for t, v in rules]
    # QuanX filter_remote requires a policy column; use the rule name and
    # override it with force-policy in the client config.
    quanx = h + [f"{QUANX_TYPE[t]},{v},{name}" for t, v in rules]
    clash = h + ["payload:"] + [
        f"  - {t},{v},no-resolve" if t in IP_TYPES else f"  - {t},{v}" for t, v in rules
    ]
    return {
        OUT / "surge" / f"{name}.list": surge,
        OUT / "loon" / f"{name}.list": loon,
        OUT / "quanx" / f"{name}.list": quanx,
        OUT / "clash" / f"{name}.yaml": clash,
    }


def main():
    check = "--check" in sys.argv
    files = {}
    for src in sorted(SRC.glob("*.list")):
        files.update(render(*parse(src)))
    stale = []
    for path, lines in files.items():
        text = "\n".join(lines) + "\n"
        if path.exists() and path.read_text(encoding="utf-8") == text:
            continue
        stale.append(path.relative_to(ROOT))
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    # remove outputs whose source was deleted
    for p in OUT.glob("*/*"):
        if p.is_file() and p not in files:
            stale.append(p.relative_to(ROOT))
            if not check:
                p.unlink()
    if check and stale:
        sys.exit("stale outputs, run python3 scripts/build.py:\n  " +
                 "\n  ".join(map(str, stale)))
    print(f"{len(files)} files, {len(stale)} {'stale' if check else 'updated'}")


if __name__ == "__main__":
    main()
